export const TOGGLE_NAV = '@@nav/TOGGLE_NAV'
export const BEGIN_PAGE_TRANSITION = '@@nav/BEGIN_PAGE_TRANSITION'
export const FINISH_PAGE_TRANSITION = '@@nav/FINISH_PAGE_TRANSITION'
export const RESET_PAGE_TRANSITION = '@@nav/RESET_PAGE_TRANSITION'

export const INIT_WORK = '@@work/INIT'
export const START_SCROLL = '@@work/START_SCROLL'
export const END_SCROLL = '@@work/END_SCROLL'
export const TOUCH_START = '@@work/TOUCH_START'
export const TOUCH_END = '@@work/TOUCH_END'