export const TOGGLE_MENU = 'TOGGLE_MENU'
export const BEGIN_PAGE_TRANSITION = 'BEGIN_PAGE_TRANSITION'
export const FINISH_PAGE_TRANSITION = 'FINISH_PAGE_TRANSITION'
export const RESET_PAGE_TRANSITION = 'RESET_PAGE_TRANSITION'