/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Background: typeof import('./components/global/Background.vue')['default']
    Button: typeof import('./components/common/Button.vue')['default']
    Carousel: typeof import('./components/global/Carousel.vue')['default']
    CovidUSA: typeof import('./components/work/items/CovidUSA.vue')['default']
    Down: typeof import('./components/global/Down.vue')['default']
    ExpandedWorkItem: typeof import('./components/work/ExpandedWorkItem.vue')['default']
    Features: typeof import('./components/work/Features.vue')['default']
    FiveHT: typeof import('./components/sections/FiveHT.vue')['default']
    FragmentShader: typeof import('./components/work/items/FragmentShader.vue')['default']
    H1: typeof import('./components/typography/H1.vue')['default']
    H2: typeof import('./components/typography/H2.vue')['default']
    Heading: typeof import('./components/hero/Heading.vue')['default']
    Hero: typeof import('./components/sections/Hero.vue')['default']
    Images: typeof import('./components/common/Images.vue')['default']
    Link: typeof import('./components/common/Link.vue')['default']
    Logo: typeof import('./components/global/Logo.vue')['default']
    Navigation: typeof import('./components/global/Navigation.vue')['default']
    NowPlaying: typeof import('./components/global/NowPlaying.vue')['default']
    P: typeof import('./components/typography/P.vue')['default']
    PlayButton: typeof import('./components/hero/PlayButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shader: typeof import('./components/common/Shader.vue')['default']
    Spinner: typeof import('./components/common/Spinner.vue')['default']
    Tags: typeof import('./components/common/Tags.vue')['default']
    Toast: typeof import('./components/common/Toast.vue')['default']
    Up: typeof import('./components/global/Up.vue')['default']
    View: typeof import('./components/layout/View.vue')['default']
    WorkItem: typeof import('./components/common/WorkItem.vue')['default']
  }
}
